development:
  adapter: mysql2
  database: followup_development
  username: root
  password:
  pool: 25
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

test:
  adapter: mysql2
  database: followup_test
  username: root
  password:
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

production:
  pool: 5
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['FOLLOWUP_HOST'] %>
  database: <%= ENV['FOLLOWUP_DB'] %>
  username: <%= ENV['FOLLOWUP_USERNAME'] %>
  password: <%= ENV['FOLLOWUP_PASSWORD'] %>
  port: 5432