development:
  adapter: mysql2
  database: followup_development
  username: root
  password:

test:
  adapter: mysql2
  database: followup_test
  username: root
  password:

production:
  pool: 10
  adapter: mysql2
  database: followup_production
  username: root
  password: