development:
  adapter: mysql2
  database: followup_development
  username: root
  password:
  pool: 25

test:
  adapter: mysql2
  database: followup_test
  username: root
  password:

production:
  pool: 10
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['FOLLOWUP_HOST'] %>
  database: <%= ENV['FOLLOWUP_DB'] %>
  username: <%= ENV['FOLLOWUP_USERNAME'] %>
  password: <%= ENV['FOLLOWUP_PASSWORD'] %>
  port: 5432